"""A script to generate the FopEvent class from a list of FOP event names."""

from pathlib import Path

# /// script
# requires-python = ">=3.9"
# ///

class_path = Path("ccsds_cop/cop_1/fop/_fop1_events.py")

events = {f"E{i}": i for i in range(1, 47)}
out_of_sequence = [
    101,
    102,
    103,
    104,
]
revisions = {
    6: "B",
    7: "B",
    8: "B",
    9: "B",
    10: "B",
    11: "B",
    12: "B",
    16: "B",
    17: "B",
    18: "B",
    21: "B",
    25: "B",
    27: "B",
    31: "B",
    32: "B",
    33: "B",
    34: "B",
    35: "B",
}

for o in out_of_sequence:
    events[f"E{o}"] = o

for i, r in revisions.items():
    s = f"E{i}"
    del events[s]
    events[s + "_" + r] = i

comment = "# DO NOT EDIT - THIS FILE IS AUTO GENERATED BY `scripts/code_gen/generate_fop_events.py`"

lines = [
    comment,
    "from ..common.fsm import CopEvent",
    "",
    "",
    "class FopEvent(CopEvent):",
]
for name, value in sorted(events.items(), key=lambda x: x[1]):
    lines.append(f"    {name} = {value}")

with class_path.open("w") as f:
    f.write("\n".join(lines) + "\n")
